name: SSH Deploy

on:
  release:
    types: [published]
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          SOURCE: "app/"
          TARGET: ${{ secrets.SSH_DIR }}
